/**
 * Section-structure ops: renumbering, duplication, and splitting.
 *
 * Imports and quick edits routinely leave two DIFFERENT sections sharing one
 * name — an importer that sees two "[Chorus]" blocks with different chords
 * has no way to know they're not the same section, so both land labeled
 * plain "Chorus". That's confusing in the arrangement list and the song
 * map, and it's a different problem from `fingerprint.ts`'s duplicate
 * detection: those sections are NOT duplicates (their content differs), they
 * just need distinguishing names. `renumberSections` is intentionally the
 * mirror image of `detectSectionMatches`'s exact-match groups.
 *
 * `duplicateSection` and `splitSection` are the two ways a user grows a
 * section into two: split when part of an existing section becomes its own
 * thing (the bars stay put, just repartitioned), duplicate when a whole
 * section is a starting point for a variant (a fresh copy, edited from
 * there). Pure module, same-reference no-op contract, ids are generated by
 * the caller (the editor's `uid()`) so these stay deterministic and testable.
 */
import { orderedSectionIds, sectionContentFingerprint, syncLinkedChords } from "./fingerprint";
import type { ArrangementItem, Bar, Line, LyricSpan, SectionDef, SongData, WordMark } from "./types";

/** Trailing arabic number, e.g. "Chorus 2" -> { base: "Chorus", num: 2 }.
 *  Roman numerals ("II Estrofa") and non-arabic suffixes are left as part
 *  of the base — only a literal digit run at the very end counts. */
const TRAILING_NUM_RE = /^(.*?)\s*(\d+)\s*$/;

function splitLabel(label: string): { base: string; num?: number } {
  const m = label.match(TRAILING_NUM_RE);
  if (!m) return { base: label.trim() };
  return { base: m[1].trim(), num: parseInt(m[2], 10) };
}

/* ------------------------------------------------------------------ */
/* Renumbering                                                         */

/**
 * Group section defs by base label (trailing number stripped, compared
 * case-insensitively) and, for every group where at least two members
 * differ in content, give every member of that group a distinct trailing
 * number: a section that already carries a number no other group member
 * has is left as-is, the rest get the lowest unused numbers in arrangement
 * order. Groups whose members are all content-identical are left alone —
 * those are merge candidates for `SectionMatchBanner`, not renumber
 * candidates. Arrangement `instanceLabel`s that exactly matched the old
 * label follow the rename; custom instance labels are untouched.
 * Same-reference no-op when no group needs a change.
 */
export function renumberSections(data: SongData): SongData {
  const groups = new Map<string, string[]>();
  for (const id of orderedSectionIds(data)) {
    const key = splitLabel(data.sections[id].label).base.toLowerCase();
    groups.set(key, [...(groups.get(key) ?? []), id]);
  }

  const relabel = new Map<string, string>();

  for (const group of groups.values()) {
    if (group.length < 2) continue;

    const fingerprints = group.map((id) => sectionContentFingerprint(data.sections[id]));
    if (fingerprints.every((fp) => fp === fingerprints[0])) continue;

    const parsed = group.map((id) => splitLabel(data.sections[id].label));
    const counts = new Map<number, number>();
    for (const p of parsed) {
      if (p.num !== undefined) counts.set(p.num, (counts.get(p.num) ?? 0) + 1);
    }
    // Numbers that uniquely identify their owner within the group stay put.
    const reserved = new Set<number>();
    parsed.forEach((p) => {
      if (p.num !== undefined && counts.get(p.num) === 1) reserved.add(p.num);
    });

    let next = 1;
    const takeNextFree = (): number => {
      while (reserved.has(next)) next++;
      reserved.add(next);
      return next;
    };

    group.forEach((id, i) => {
      const p = parsed[i];
      const hasValidUniqueNum = p.num !== undefined && counts.get(p.num) === 1;
      const num = hasValidUniqueNum ? (p.num as number) : takeNextFree();
      const newLabel = `${p.base} ${num}`;
      if (newLabel !== data.sections[id].label) relabel.set(id, newLabel);
    });
  }

  if (relabel.size === 0) return data;

  const sections: SongData["sections"] = { ...data.sections };
  for (const [id, label] of relabel) {
    sections[id] = { ...sections[id], label };
  }

  const arrangement = data.arrangement.map((a) => {
    const newLabel = relabel.get(a.ref);
    if (newLabel && a.instanceLabel === data.sections[a.ref].label) {
      return { ...a, instanceLabel: newLabel };
    }
    return a;
  });

  return { ...data, sections, arrangement };
}

/* ------------------------------------------------------------------ */
/* Shared naming helper for duplicate/split                            */

/**
 * The next free "<base> <n>" label for a new section sharing `sourceLabel`'s
 * base. A bare, unnumbered section ("Verse") is treated as occupying number
 * 1 the way people already read it, so its first sibling becomes "Verse 2"
 * rather than "Verse 1". Falls back to "<label> (copy)" when the source
 * label is nothing but digits (no usable base to number) — deliberately the
 * simplest deterministic option for that edge case.
 */
function nextFreeLabel(data: SongData, sourceLabel: string): string {
  const { base } = splitLabel(sourceLabel);
  if (!base) return `${sourceLabel} (copy)`;

  const baseKey = base.toLowerCase();
  const used = new Set<number>();
  for (const def of Object.values(data.sections)) {
    const p = splitLabel(def.label);
    if (p.base.toLowerCase() === baseKey) used.add(p.num ?? 1);
  }
  let n = 1;
  while (used.has(n)) n++;
  return `${base} ${n}`;
}

/* ------------------------------------------------------------------ */
/* Duplicate                                                           */

function cloneMark(m: WordMark): WordMark {
  return { ...m };
}

function cloneLyric(s: LyricSpan): LyricSpan {
  return { ...s, marks: s.marks ? s.marks.map(cloneMark) : undefined };
}

function cloneBar(b: Bar): Bar {
  return { chords: b.chords.map((c) => ({ ...c })) };
}

function cloneLine(l: Line): Line {
  return { bars: l.bars.map(cloneBar), lyrics: l.lyrics.map(cloneLyric) };
}

/**
 * Copy section `id` to a new section `newId`: a deep copy (fresh bar/chord/
 * lyric/mark objects throughout — the copy and the original never share a
 * reference, so editing one can't leak into the other), given a
 * distinguishing label since starting-out-identical content means
 * `renumberSections` won't touch it (that's a merge candidate, not a
 * renumber one). One arrangement instance is inserted right after the
 * source's last instance; sections with no arrangement instance are
 * appended at the end. Same-reference no-op when `id` doesn't exist.
 */
export function duplicateSection(data: SongData, id: string, newId: string): SongData {
  const src = data.sections[id];
  if (!src) return data;

  const label = nextFreeLabel(data, src.label);
  const sections: SongData["sections"] = {
    ...data.sections,
    [newId]: { label, color: src.color, lines: src.lines.map(cloneLine) },
  };

  let lastIdx = -1;
  data.arrangement.forEach((a, i) => {
    if (a.ref === id) lastIdx = i;
  });
  const insertAt = lastIdx === -1 ? data.arrangement.length : lastIdx + 1;
  const newItem: ArrangementItem = { ref: newId, instanceLabel: label };
  const arrangement = [...data.arrangement];
  arrangement.splice(insertAt, 0, newItem);

  return { sections, arrangement };
}

/* ------------------------------------------------------------------ */
/* Split                                                                */

/**
 * Split section `id` at line index `atLine`: lines [0, atLine) stay in the
 * original, lines [atLine, end) move to a new section `newId` (same color,
 * a distinguishing label). Every arrangement instance of the original gets
 * a matching instance of the new section right after it; an instance with
 * `repeat > 1` expands into that many consecutive original+new pairs
 * (repeat lost on the pieces — (AB)x2 is ABAB, not a single AABB pair), and
 * the original's `repeat` is dropped since each expanded copy plays once.
 * The original's bar count changed, so `syncLinkedChords` runs on the
 * result to honestly sever any `sameChordsAs` link whose bar count no
 * longer matches. Same-reference no-op for an out-of-range `atLine`
 * (<= 0 or >= the section's line count — there's nothing to split off).
 */
export function splitSection(
  data: SongData,
  id: string,
  atLine: number,
  newId: string
): SongData {
  const src = data.sections[id];
  if (!src) return data;
  if (atLine <= 0 || atLine >= src.lines.length) return data;

  const keepLines = src.lines.slice(0, atLine);
  const moveLines = src.lines.slice(atLine);
  const newLabel = nextFreeLabel(data, src.label);

  const sections: SongData["sections"] = {
    ...data.sections,
    [id]: { ...src, lines: keepLines },
    [newId]: { label: newLabel, color: src.color, lines: moveLines },
  };

  const arrangement: ArrangementItem[] = [];
  for (const item of data.arrangement) {
    if (item.ref !== id) {
      arrangement.push(item);
      continue;
    }
    const repeatCount = item.repeat ?? 1;
    const { repeat: _repeat, ...rest } = item;
    for (let i = 0; i < repeatCount; i++) {
      arrangement.push({ ...rest });
      arrangement.push({ ref: newId, instanceLabel: newLabel });
    }
  }

  return syncLinkedChords({ sections, arrangement });
}
